### ISSUE TITLE
Schematic is inaccurate 

### ISSUE THREAD

**Issue by stiliajohny** [OpenInterpreter/01#163]
**Describe the bug**
The schematic on [here](https://github.com/OpenInterpreter/01/blob/4be9861fb76b21e7ecfcd7c63e49d81977109ff6/hardware/light/Labeled%20Wiring%20Diagram.png) is inaccurate as it references an amplifier but it is a power charging circuit 

**To Reproduce**
- visit the [schematic](https://github.com/OpenInterpreter/01/blob/4be9861fb76b21e7ecfcd7c63e49d81977109ff6/hardware/light/Labeled%20Wiring%20Diagram.png)

**Expected behavior**
Replace the text with the part description 

**Screenshots**
https://github.com/OpenInterpreter/01/blob/4be9861fb76b21e7ecfcd7c63e49d81977109ff6/hardware/light/Labeled%20Wiring%20Diagram.png

**Desktop (please complete the following information):**
 N/A

**Additional context**

**Comment by hpsaturn** [comment]
Do you know why we need a second switch? what is the reason if the echo has one. ?

**Comment by tyfiero** [comment]
Good question. We added the switch to reliably turn on and off the unit when connected to battery, I didn't realize that the echo has a switch. The switch is wired to the charging board and not the device, does that matter? I'd love to hear your thoughts on this, if we don't need another switch then I don't see why we should have it.

**Comment by tyfiero** [comment]
Also, PR #183 fixes the schematic.

**Comment by hpsaturn** [comment]
I'm new here and also I'm new with the M5Echo, but I know about the some M5 devices, and is possible that with the builtin button we can do that, and maybe is enough, for example if we using a board like this for handled the power and suspend of the device:

![photo_2024-03-29_02-13-00](https://github.com/OpenInterpreter/01/assets/423856/2f0d1c20-d6a9-4cbe-a1f9-97f3ec0393a9)

https://docs.m5stack.com/en/module/StampTimerPower

because the communication with the board is via I2C and we could go to deep-sleep via software, for instance a long press with the echo button, and then do a wake-up with this extra button of this StampTimerPower. Well, I need test that, but I think that is possible.

**Comment by tyfiero** [comment]
That's an interesting idea. Get rid of the switch altogether, and just triple click the button to power on or off. Then we would only need the one button, right? No need for two buttons or a switch. Turn on and off with the primary button

**Comment by hpsaturn** [comment]
Yes, but keep in mind that sometimes you need different levels of "power-off", light-sleep and deep-sleep on the M5Echo are ok, but for deep-sleep via the RTC board (the best option for ultra low power consumption), you would need a wakeup it via its button (the button in this module)

**Comment by stiliajohny** [comment]
as per BOM there is an amplifier, would you consider adding the amplifier as optional on the diagram ?
