### ISSUE TITLE
 PyAudio ImportError: symbol not found in flat namespace '_PaMacCore_SetupChannelMap'

### ISSUE THREAD

**Issue by matmult** [OpenInterpreter/01#68]
Running on M2 MBP in a conda environment. 

To reproduce, 1) create conda env with python=3.10 2) brew install requirements 3) pip install 01OS 4) run 01.

This could be a conda/arm architecture issue, see relevant stackoverflow: https://stackoverflow.com/questions/69909054/could-not-import-the-pyaudio-c-module-portaudio-mac-m1-about-symbol-not-f

**Comment by shivenmian** [comment]
This is an issue with one or both of:

1. your brew (and hence portaudio) installation
2. your pyaudio installation

First, try to follow [this answer](https://stackoverflow.com/a/69833329) to see if it works. 

If it doesn't, you may need to reinstall Brew:

Brew is installed in /usr/local in older Intel / Rosetta Macs, but installs in /opt/homebrew now. You can use `which brew` to find out where brew is installed. Incase it is still on `/usr/local`, you'll need to uninstall brew from there and install in /opt/homebrew, since Pyaudio will also pick it up from there. Follow [these steps](https://github.com/orgs/Homebrew/discussions/417#discussioncomment-2556937) to fix Brew.

Once brew is fixed, uninstall pyaudio, then reinstall it using the Stackoverflow link.

**Comment by keldenl** [comment]
unfortunately running into similar issues on m1 pro, tried the above suggestions to no avail

**Comment by shahdivax** [comment]
```
sudo apt-get update
sudo apt-get install portaudio19-dev
```
@keldenl this worked for ubuntu for me, you can try similar and might just work

**Comment by keldenl** [comment]
i was actually able to fix this issue another way – setting up my own conda env (make sure to do python version 3.11.8, due to another issue):
```
CONDA_SUBDIR=osx-arm64 conda create -n MY_ENV python python=3.11.8
```

and then thanks to https://stackoverflow.com/questions/33513522/when-installing-pyaudio-pip-cannot-find-portaudio-h-in-usr-local-include/69833329#69833329

```
conda activate
poetry install
pip uninstall pyaudio
pip install --global-option='build_ext' --global-option="-I$(brew --prefix)/include" --global-option="-L$(brew --prefix)/lib" pyaudio
```

and then running it with `--local` did the trick!

**Comment by tyfiero** [comment]
Seems like this is sorted out now, thanks @shahdivax, @keldenl and @shivenmian for your help!

**Comment by Linfeng1505** [comment]
I am still not sort this out using you guys mentioned solutions.. But I first `import sounddevice` and then `import pyaudio`. This works! Maybe the `portaudio` is linked by the `sounddevice`, and then the `pyaudio` package works. Im using m1pro chip btw.

**Comment by btilongnguyen** [comment]
I'm using a conda environment and this works for me:
```
conda install pyaudio
```

**Comment by ycchuang** [comment]
`conda update --all` 
`conda install pyaudio` 
works on m3
